//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication2.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class feemapping
    {
        public int fid { get; set; }
        public int admissionnum { get; set; }
        public string studentname { get; set; }
        public string fathername { get; set; }
        public int classid { get; set; }
        public int schoolfee { get; set; }
        public string busfee { get; set; }
    
        public virtual @class @class { get; set; }
    }
}
