//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication2.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class payment
    {
        public int pid { get; set; }
        public string paymentname { get; set; }
        public string studnetname { get; set; }
        public int feepaid { get; set; }
        public int feepending { get; set; }
        public int totalfee { get; set; }
        public System.DateTime lastpaiddate { get; set; }
        public int classid { get; set; }
        public bool islastpay { get; set; }
        public bool isactive { get; set; }
        public Nullable<int> admissionnum { get; set; }
    
        public virtual @class @class { get; set; }
    }
}
