//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication2.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class subjectmapping
    {
        public int smid { get; set; }
        public Nullable<int> subid { get; set; }
        public Nullable<int> classid { get; set; }
    
        public virtual @class @class { get; set; }
        public virtual subjectt subjectt { get; set; }
    }
}
