//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication2.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class Teacher
    {
        public int tid { get; set; }
        public string Tname { get; set; }
        public string fathername { get; set; }
        public string phonenumber { get; set; }
        public Nullable<System.DateTime> dateofbirth { get; set; }
        public string gender { get; set; }
        public string adress { get; set; }
        public byte[] photo { get; set; }
        public Nullable<System.DateTime> dateofjoing { get; set; }
        public Nullable<int> rid { get; set; }
        public Nullable<bool> isactive { get; set; }
        public string Email { get; set; }
        public string Password { get; set; }
    
        public virtual Role Role { get; set; }
    }
}
